{
  "openapi": "3.0.0",
  "info": {
    "title": "Mock Api Portfolio",
    "version": "1.0.0",
    "contact": {
      "url": "http://xosedev.com/",
      "email": "xosedev@gmail.com",
      "name": "xosedev"
    },
    "description": "xosedev Mock API Open API Definitions",
    "license": {
      "name": "private"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3000/api"
    }
  ],
  "paths": {
    "/menus": {
      "get": {
        "summary": "Obtain Menus",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/menus"
                  }
                },
                "examples": {
                  "menu": {
                    "$ref": "#/components/examples/menus"
                  }
                }
              }
            }
          }
        },
        "operationId": "get_menus",
        "description": "Obtain menus",
        "tags": [
          "Data"
        ]
      },
      "parameters": []
    },
    "/skills": {
      "get": {
        "summary": "Obtain Skills",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/skills"
                  }
                },
                "examples": {
                  "menu": {
                    "$ref": "#/components/examples/skills"
                  }
                }
              }
            }
          }
        },
        "operationId": "get_skills",
        "description": "Obtain skills",
        "tags": [
          "Data"
        ]
      },
      "parameters": []
    },
    "/links": {
      "get": {
        "summary": "Obtain links",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/links"
                  }
                },
                "examples": {
                  "menu": {
                    "$ref": "#/components/examples/links"
                  }
                }
              }
            }
          }
        },
        "operationId": "get_links",
        "description": "Obtain links",
        "tags": [
          "Data"
        ]
      },
      "parameters": []
    },
    "/projects": {
      "get": {
        "summary": "Obtain projects",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/projects"
                  }
                },
                "examples": {
                  "menu": {
                    "$ref": "#/components/examples/projects"
                  }
                }
              }
            }
          }
        },
        "operationId": "get_projects",
        "description": "Obtain projects",
        "tags": [
          "Data"
        ]
      },
      "parameters": []
    },
    "/owner": {
      "get": {
        "summary": "Obtain owner portfolio information",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/owner"
                },
                "examples": {
                  "user": {
                    "$ref": "#/components/examples/owner"
                  }
                }
              }
            }
          }
        },
        "operationId": "get_menus",
        "description": "Obtain menus",
        "tags": [
          "Data"
        ]
      },
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "owner": {
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "lastName": {
            "type": "string",
            "minLength": 1
          },
          "mail": {
            "type": "string",
            "minLength": 1
          },
          "img": {
            "type": "string",
            "minLength": 1
          },
          "desc": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id",
          "name",
          "lastName",
          "mail",
          "img"
        ],
        "x-examples": {
          "menu-1": {
            "id": "1a470c8e-40ed-4c2d-b590-a4f1f6ead6cc",
            "name": "Inicio"
          }
        }
      },
      "menus": {
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id",
          "name"
        ],
        "x-examples": {
          "menu-1": {
            "id": "1a470c8e-40ed-4c2d-b590-a4f1f6ead6cc",
            "name": "Inicio"
          }
        }
      },
      "skills": {
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "tecnologies": {
            "type": "array",
            "minLength": 1,
            "items": [
              {
                "id": {
                  "type": "string",
                  "minLength": 1
                },
                "name": {
                  "type": "string",
                  "minLength": 1
                },
                "value": {
                  "type": "number",
                  "minLength": 1
                }
              }
            ]
          }
        },
        "required": [
          "id",
          "name",
          "tecnologies"
        ],
        "x-examples": {
          "menu-1": {
            "id": "1a470c8e-40ed-4c2d-b590-a4f1f6ead6cc",
            "name": "Java",
            "value": "100"
          }
        }
      },
      "links": {
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "icon": {
            "type": "string",
            "minLength": 1
          },
          "url": {
            "type": "string",
            "minLength": 1
          },
          "view": {
            "type": "bool"
          }
        },
        "required": [
          "id",
          "name",
          "icon",
          "url",
          "view"
        ],
        "x-examples": {
          "link-1": {
            "id": "1",
            "name": "Inicio"
          }
        }
      },
      "projects": {
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          }
          ,
          "desc": {
            "type": "string",
            "minLength": 1
          },
          "img": {
            "type": "string",
            "minLength": 1
          },
          "url": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id",
          "name",
          "desc",
          "img",
          "url"
        ],
        "x-examples": {
          "project-1": {
            "id": "1",
            "name": "Inicio",
            "desc": "www",
            "img": "www",
            "url": "www"
          }
        }
      },
      "works": {
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          }
          ,
          "tecnologies": {
            "type": "string",
            "minLength": 1
          },
          "projects": {
            "type": "string",
            "minLength": 1
          },
          "img": {
            "type": "string",
            "minLength": 1
          },
          "url": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id",
          "name",
          "tecnologies",
          "projects",
          "img",
          "url"
        ],
        "x-examples": {
          "project-1": {
            "id": "1",
            "name": "Inicio",
            "tecnologies": "www",
            "projects": "www",
            "img": "www",
            "url": "www"
          }
        }
      }
    },
    "securitySchemes": {},
    "examples": {
      "owner": {
        "value": {
          "id":"1",
          "name":"Jose",
          "lastName":"Toro",
          "mail":"xosedev@gmail.com",
          "img":"https://www.xosedev.com/.uploads/user.jpg",
          "desc": "Software Developer"
        }
      },
      "menus": {
        "value": [
          {
            "id": "/",
            "name": "Home",
            "status": "on"
          },
          {
            "id": "blog",
            "name": "Blog",
            "status": "off"
          },
          {
            "id": "about-me",
            "name": "About Me",
            "status": "on"
          },
          {
            "id": "works",
            "name": "Works",
            "status": "on"
          },
          {
            "id": "projects",
            "name": "Projects (Experimental)",
            "status": "on"
          },
         
          {
            "id": "games",
            "name": "Game studio",
            "status": "off"
          },
          {
            "id": "links",
            "name": "Links",
            "status": "on"
          },
          {
            "id": "contact",
            "name": "Contact",
            "status": "on"
          }
        ]
      },
      "skills": {
        "value": [
          {
            "id": "1",
            "name": "Developer",
            "tecnologies": [
              {
                "id": "1",
                "name": "Java",
                "value": "90"
              },
              {
                "id": "2",
                "name": "TypeScript",
                "value": "70"
              },
              {
                "id": "3",
                "name": "JavaScript",
                "value": "70"
              },
              {
                "id": "4",
                "name": "HTML",
                "value": "70"
              },
              {
                "id": "5",
                "name": "CSS",
                "value": "60"
              },
              {
                "id": "6",
                "name": "SQL",
                "value": "80"
              }
            ]
          },
          {
            "id": "2",
            "name": "Framework and Libraries",
            "tecnologies": [
              {
                "id": "1",
                "name": "Node Js",
                "value": "80"
              },
              {
                "id": "2",
                "name": "Zk Framework",
                "value": "90"
              },
              {
                "id": "3",
                "name": "Angular",
                "value": "80"
              },
              {
                "id": "4",
                "name": "React",
                "value": "80"
              },
              {
                "id": "5",
                "name": "React Native",
                "value": "60"
              },
              {
                "id": "6",
                "name": "PrimeFaces",
                "value": "80"
              }
            ]
          }
        ]
      },
      "links": {
        "value": [
          {
            "id": "1",
            "name": "Instagram",
            "icon": "https://www.xosedev.com/.uploads/icons/instagram.png",
            "url": "https://www.instagram.com/xosedev/",
            "view": true
          },
          {
            "id": "2",
            "name": "GitHub",
            "icon": "https://www.xosedev.com/.uploads/icons/github.png",
            "url": "https://github.com/xosedev",
            "view": true
          },
          {
            "id": "3",
            "name": "Linkedin",
            "icon": "https://www.xosedev.com/.uploads/icons/linkedin.png",
            "url": "https://www.linkedin.com/in/xosedev/",
            "view": true
          },
          {
            "id": "4",
            "name": "Twitch",
            "icon": "https://www.xosedev.com/.uploads/icons/twitch.png",
            "url": "https://www.twitch.tv/xosedev",
            "view": true
          },{
            "id": "5",
            "name": "Youtube",
            "icon": "https://www.xosedev.com/.uploads/icons/youtube.png",
            "url": "https://www.youtube.com/channel/UCqeqxQh83EZ_PvcpSHAtgyg",
            "view": true
          },{
            "id": "6",
            "name": "TikTok",
            "icon": "https://www.xosedev.com/.uploads/icons/tiktok.png",
            "url": "https://www.tiktok.com/@xosedev",
            "view": true
          }
        ]
      },
      "projects": {
        "value": [
          {
            "id": "1",
            "name": "Portfolio Orchestrator",
            "desc": ["Node Js", "TypeScript", "Express", "OpenApi"],
            "img":"https://cdn.neow.in/news/images/uploaded/2021/04/1619644762_github-desktop_story.jpg",
            "url":"https://github.com/xosedev/my-portfolio-orchestrator"
          },
          {
            "id": "2",
            "name": "Portfolio Api",
            "desc": ["Node Js", "TypeScript", "Express", "OpenApi", "PostgreSQL"],
            "img":"https://cdn.neow.in/news/images/uploaded/2021/04/1619644762_github-desktop_story.jpg",
            "url":"https://github.com/xosedev/my-portfolio-api"
          },
          {
            "id": "3",
            "name": "Portfolio Web",
            "desc": ["React", "Redux", "MUI", "Tailwind"],
            "img":"https://cdn.neow.in/news/images/uploaded/2021/04/1619644762_github-desktop_story.jpg",
            "url":"https://github.com/xosedev/my-portfolio-frontend"
          },
          {
            "id": "4",
            "name": "Shortcuts Manager front",
            "desc": ["React", "Redux", "MUI", "Tailwind"],
            "img":"https://cdn.neow.in/news/images/uploaded/2021/04/1619644762_github-desktop_story.jpg",
            "url":"https://github.com/xosedev/shortcut-manager-frontend"
          },{
            "id": "5",
            "name": "Shortcuts Manager Backend",
            "desc": ["Node Js", "TypeScript", "Express", "OpenApi", "PostgreSQL"],
            "img":"https://cdn.neow.in/news/images/uploaded/2021/04/1619644762_github-desktop_story.jpg",
            "url":"https://github.com/xosedev/shortcut-manager-backend"
          },
          {
            "id": "6",
            "name": "Mail Api",
            "desc": ["Node Js", "TypeScript", "Express", "OpenApi", "Nodemailer"],
            "img":"https://cdn.neow.in/news/images/uploaded/2021/04/1619644762_github-desktop_story.jpg",
            "url":"https://github.com/xosedev/my-mail-api"
          }
        ]
      },
      "works": {
        "value": [
          {
            "id": "1",
            "name": "NTTDATA Chile",
            "tecnologies": ["Java", "Spring Framework", "ZK Framework", "PostgreSQL", "CSS", "Html", "Javascript", "Git", "SVN"],
            "projects": ["Movistar Personas", "Entel Personas", "Banco Sabadel","Correos España","EhCos Clinic", "EhCos Clinic Mexico", "EhCos Clinic España"],
            "img":"https://www.xosedev.com/.uploads/icons/nttdata.jpg",
            "url":"https://cl.nttdata.com/about-us"
          },
          {
            "id": "2",
            "name": "Indra Sistemas Chile",
            "tecnologies": ["Java", "Spring Framework", "Angular/Angular JS", "PostgreSQL", "CSS", "Html", "Javascript", "TypeScript", "Git", "Swagger/Open Api"],
            "projects": ["Solicitudes Bancarias BBVA", "Ficha 360 BBVA", "Margenes Estatales BBVA"],
            "img":"https://www.xosedev.com/.uploads/icons/indra.jpeg",
            "url":"https://www.indracompany.com/es"
          },
          {
            "id": "3",
            "name": "BBVA - Scotiabank",
            "tecnologies": ["Java", "Spring Framework", "Angular/Angular JS", "PostgreSQL", "CSS", "Html", "Javascript", "TypeScript", "Git", "Swagger/Open Api", "Jenkins", "AWS"],
            "projects": ["Solicitudes Bancarias BBVA", "Ficha 360 BBVA", "Margenes Estatales BBVA", "Devops"],
            "img":"https://www.xosedev.com/.uploads/icons/sb.png",
            "url":"https://www.scotiabankchile.cl/"
          },
          {
            "id": "4",
            "name": "Altiuz SPA",
            "tecnologies": ["Java", "Spring Boot", "Angular/Angular JS", "PostgreSQL", "CSS", "Html", "Javascript", "TypeScript", "Git", "Swagger/Open Api", "Jenkins", "GCP"],
            "projects": ["Tarjeta Cruz Blanca", "Claroo Chile Cartolas", "Tasacion fiscal SII", "Agendamiento remoto MINSAL","Compras importadas Hites"],
            "img":"https://www.xosedev.com/.uploads/icons/altiuz.png",
            "url":"https://altiuz.com/"
          },{
            "id": "5",
            "name": "Ripley Chile",
            "tecnologies": ["Node Js", "TypeScript", "Express","React","OpenApi","Microfrontend","GCP", "Firebase"],
            "projects": ["Rcenter - admin marketplace"],
            "img":"https://www.xosedev.com/.uploads/icons/ripley.png",
            "url":"https://simple.ripley.cl/"
          },{
            "id": "6",
            "name": "Falabella Chile",
            "tecnologies": ["React","React Native","Node Js", "TypeScript", "Express","OpenApi","GCP", "KeyCloack", "Firebase"],
            "projects": ["SOS"],
            "img":"https://www.xosedev.com/.uploads/icons/falabella.png",
            "url":"https://www.falabella.com/falabella-cl"
          }
        ]
      }
    },
    "responses": {}
  },
  "tags": [
    {
      "name": "Data",
      "description": "Data of portfolio"
    }
  ]
}
