{
  "openapi": "3.0.0",
  "info": {
    "title": "Mock Api Portfolio",
    "version": "1.0.0",
    "contact": {
      "url": "http://xosedev.com/",
      "email": "xosedev@gmail.com",
      "name": "xosedev"
    },
    "description": "xosedev Mock API Open API Definitions",
    "license": {
      "name": "private"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3000/api"
    }
  ],
  "paths": {
    "/menus": {
      "get": {
        "summary": "Obtain Menus",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/menus"
                  }
                },
                "examples": {
                  "menu": {
                    "$ref": "#/components/examples/menus"
                  }
                }
              }
            }
          }
        },
        "operationId": "get_menus",
        "description": "Obtain menus",
        "tags": [
          "Data"
        ]
      },
      "parameters": []
    },
    "/links": {
      "get": {
        "summary": "Obtain links",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/links"
                  }
                },
                "examples": {
                  "menu": {
                    "$ref": "#/components/examples/links"
                  }
                }
              }
            }
          }
        },
        "operationId": "get_links",
        "description": "Obtain links",
        "tags": [
          "Data"
        ]
      },
      "parameters": []
    },
    "/projects": {
      "get": {
        "summary": "Obtain projects",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/projects"
                  }
                },
                "examples": {
                  "menu": {
                    "$ref": "#/components/examples/projects"
                  }
                }
              }
            }
          }
        },
        "operationId": "get_projects",
        "description": "Obtain projects",
        "tags": [
          "Data"
        ]
      },
      "parameters": []
    },
    "/owner": {
      "get": {
        "summary": "Obtain owner portfolio information",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/owner"
                },
                "examples": {
                  "user": {
                    "$ref": "#/components/examples/owner"
                  }
                }
              }
            }
          }
        },
        "operationId": "get_menus",
        "description": "Obtain menus",
        "tags": [
          "Data"
        ]
      },
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "user": {
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "lastName": {
            "type": "string",
            "minLength": 1
          },
          "mail": {
            "type": "string",
            "minLength": 1
          },
          "img": {
            "type": "string",
            "minLength": 1
          },
          "desc": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id",
          "name",
          "lastName",
          "mail",
          "img"
        ],
        "x-examples": {
          "menu-1": {
            "id": "1a470c8e-40ed-4c2d-b590-a4f1f6ead6cc",
            "name": "Inicio"
          }
        }
      },
      "menus": {
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id",
          "name"
        ],
        "x-examples": {
          "menu-1": {
            "id": "1a470c8e-40ed-4c2d-b590-a4f1f6ead6cc",
            "name": "Inicio"
          }
        }
      },
      "links": {
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "icon": {
            "type": "string",
            "minLength": 1
          },
          "url": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id",
          "name",
          "icon",
          "url"
        ],
        "x-examples": {
          "link-1": {
            "id": "1",
            "name": "Inicio"
          }
        }
      },
      "projects": {
        "description": "",
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          }
          ,
          "desc": {
            "type": "string",
            "minLength": 1
          },
          "img": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "id",
          "name",
          "desc",
          "img"
        ],
        "x-examples": {
          "project-1": {
            "id": "1",
            "name": "Inicio",
            "desc": "www",
            "img": "www"
          }
        }
      }
    },
    "securitySchemes": {},
    "examples": {
      "owner": {
        "value": {
          "id":"1",
          "name":"Jose",
          "lastName":"Toro",
          "mail":"xosedev@gmail.com",
          "img":"https://www.xosedev.com/.uploads/user.jpg",
          "desc": "Software Developer"
        }
      },
      "menus": {
        "value": [
          {
            "id": "/",
            "name": "Inicio",
            "status": "on"
          },
          {
            "id": "blog",
            "name": "Blog",
            "status": "off"
          },
          {
            "id": "about-me",
            "name": "AboutMe",
            "status": "off"
          },
          {
            "id": "projects",
            "name": "Projects",
            "status": "on"
          },
          {
            "id": "games",
            "name": "Game studio",
            "status": "on"
          },
          {
            "id": "links",
            "name": "Links",
            "status": "on"
          },
          {
            "id": "contact",
            "name": "Contact",
            "status": "on"
          }
        ]
      },
      "links": {
        "value": [
          {
            "id": "1",
            "name": "Instagram",
            "icon": "https://www.xosedev.com/.uploads/icons/instagram.png",
            "url": "https://www.instagram.com/xosedev/"
          },
          {
            "id": "2",
            "name": "GitHub",
            "icon": "https://www.xosedev.com/.uploads/icons/github.png",
            "url": "https://github.com/xosedev"
          },
          {
            "id": "3",
            "name": "Linkedin",
            "icon": "https://www.xosedev.com/.uploads/icons/linkedin.png",
            "url": "https://www.linkedin.com/in/xosedev/"
          },
          {
            "id": "4",
            "name": "Twitch",
            "icon": "https://www.xosedev.com/.uploads/icons/twitch.png",
            "url": "https://www.twitch.tv/xosedev"
          },{
            "id": "5",
            "name": "Youtube",
            "icon": "https://www.xosedev.com/.uploads/icons/youtube.png",
            "url": "https://www.youtube.com/channel/UCqeqxQh83EZ_PvcpSHAtgyg"
          }
        ]
      },
      "projects": {
        "value": [
          {
            "id": "1",
            "name": "Portfolio Orchestrator",
            "desc": "on",
            "img":"https://images.unsplash.com/photo-1471357674240-e1a485acb3e1"
          },
          {
            "id": "2",
            "name": "Portfolio Api",
            "desc": "on",
            "img":"https://images.unsplash.com/photo-1471357674240-e1a485acb3e1"
          },
          {
            "id": "3",
            "name": "Portfolio Web",
            "desc": "on",
            "img":"https://images.unsplash.com/photo-1471357674240-e1a485acb3e1"
          },
          {
            "id": "4",
            "name": "InuDesk",
            "desc": "on",
            "img":"https://images.unsplash.com/photo-1471357674240-e1a485acb3e1"
          }
        ]
      }
    },
    "responses": {}
  },
  "tags": [
    {
      "name": "Data",
      "description": "Data of portfolio"
    }
  ]
}
